---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    application: "exim4"
    role: "smtp"
  name: "smtp"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: "exim4"
      role: "smtp"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        application: "exim4"
        role: "smtp"
    spec:
      volumes:
        - name: "etc-mailname"
          configMap:
            name: "etc-mailname"
            items:
              - key: "mailname"
                path: "mailname"
      containers:
        - name: "exim4"
          image: "tianon/exim4:latest"
          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: "100m"
              memory: "16Mi"
            requests:
              cpu: "100m"
              memory: "16Mi"
          securityContext:
            privileged: false
          ports:
            - containerPort: 25
              protocol: "TCP"
              name: "smtp"
          volumeMounts:
            - name: "etc-mailname"
              readOnly: true
              mountPath: "/etc"
          livenessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: "smtp"
            initialDelaySeconds: 5
            timeoutSeconds: 1
      restartPolicy: "Always"
      securityContext: {}
